title: DATA CONTEST
description: DATA CONTEST

# disabled because we are using a custom domain
url: https://TEAM-Dbulb.github.io # the base hostname & protocol for your site
baseurl: /data-contest-page # the subpath of your site, e.g. /blog/

color-scheme: "#5C73F2" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
